### ISSUE TITLE
Help to run your project for learning purpose

### ISSUE THREAD

**Issue by ShahriyarHridoy** [davoszabo/flutter-django-recipeapp#1]
i found your project interesting after reading the project description. But i am little bit confused how can i run your django web backend and run your model. Actually i am a flutter dev but i want to learn the backend as well with machine learning model. so I believe your project will be my best learning material. can you please add the step by step process how can i run and deploy your project in local server including the machine learning model

**Comment by davoszabo** [comment]
Hi! I am glad you find my project interesting, but unfortunately I am not planning to further maintain it! I'll update the documentation in some part, but my memories are kinda rusty so I need to refresh it first :). As soon as I have time, I get in to it.

**Comment by ShahriyarHridoy** [comment]
> Hi! I am glad you find my project interesting, but unfortunately I am not planning to further maintain it! I'll update the documentation in some part, but my memories are kinda rusty so I need to refresh it first :). As soon as I have time, I get in to it.

thank you for your help. I am waiting your response. Hope you will update it soon.

**Comment by davoszabo** [comment]
I've updated several parts in backend and in model to be stable enough. The documentation is also updated in main README.md. Please take a look, although it might be quite comprehensive. I couldn't test it out on my system unfortunately, because the connection hasn't been established between the frontend and backend due to CORS issues. As I said I am not planning to further maintain this project, but hope it is stable enough to begin your journey with it :).

**Comment by davoszabo** [comment]
EDIT: managed to fix CORS and another thing, and the app seems OK to me :)
